DBWT/Controllers/HomeController.cs
using System.Web.Mvc;
using System.Collections.Specialized;

using DBWT.Models;

namespace DBWT.Controllers
{
    public class HomeController : Controller
    {
        // GET: Start
        public ActionResult Index()
        {
            NameValueCollection nvc = Request.Form;

            Login log = new Login();

            LoginManagement.Login(Session, nvc, log);
            ViewBag.Anzahl = CookieManagement.GetAnzahl(HttpContext, Session);
            return View(log);
        }
    }
}

DBWT/Controllers/LoginController.cs
using System.Web.Mvc;
using System.Collections.Specialized;
using DBWT.Models;

namespace DBWT.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            NameValueCollection nvc = Request.Form;

            Login log = new Login();
            
            LoginManagement.Login(Session, nvc, log);
            ViewBag.Anzahl = CookieManagement.GetAnzahl(HttpContext, Session);
            return View(log);
        }
    }
}

DBWT/Controllers/ProdukteController.cs
using System.Web.Mvc;
using DBWT.Models;

namespace DBWT.Controllers
{
    public class ProdukteController : Controller
    {
        // GET: Produkte
        public ActionResult Index()
        {
            Produkte pro = new Produkte();

            if(Request.QueryString["kategorie"] != null)
            {
                pro.KategorieG = short.Parse(Request.QueryString["kategorie"]);
            }
            else
            {
                pro.KategorieG = 0;
            }

            pro.VeganG = Request.QueryString["vegan"];
            pro.VegetarischG = Request.QueryString["vegetarisch"];
            pro.VerfuegbarG = Request.QueryString["verfuegbar"];

            pro.ProdukteListe();
            pro.KategorienListe();

            ViewBag.Anzahl = CookieManagement.GetAnzahl(HttpContext, Session);
            return View(pro);
        }
    }
}

DBWT/Controllers/RegistrierungController.cs
using System.Web.Mvc;
using System.Collections.Specialized;

using DBWT.Models;

namespace DBWT.Controllers
{
    public class RegistrierungController : Controller
    {
        // GET: Registrierung
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Student()
        {
            NameValueCollection nvc = Request.Form;

            Registrierung reg = new Registrierung
            {
                Role = "Student",
                Vorname = nvc["vorname"],
                Nachname = nvc["nachname"],
                Geburtsjahr = nvc["geburtsjahr"],
                Geburtsmonat = nvc["geburtsmonat"],
                Geburtstag = nvc["geburtstag"],

                Email = nvc["email"],
                Nutzername = nvc["nutzername"],
                Password = nvc["password"],
                PasswordVerify = nvc["passwordVerify"],

                Studiengang = nvc["studiengang"],
                Matrikelnummer = nvc["matrikelnummer"]
            };

            reg.NewUser();

            ViewBag.Anzahl = CookieManagement.GetAnzahl(HttpContext, Session);
            return View(reg);
        }

        public ActionResult Mitarbeiter()
        {
            NameValueCollection nvc = Request.Form;

            Registrierung reg = new Registrierung
            {
                Role = "Mitarbeiter",
                Vorname = nvc["vorname"],
                Nachname = nvc["nachname"],
                Geburtsjahr = nvc["geburtsjahr"],
                Geburtsmonat = nvc["geburtsmonat"],
                Geburtstag = nvc["geburtstag"],

                Email = nvc["email"],
                Nutzername = nvc["nutzername"],
                Password = nvc["password"],
                PasswordVerify = nvc["passwordVerify"],

                Buero = nvc["buero"],
                Telefon = nvc["telefon"]
            };

            reg.NewUser();

            ViewBag.Anzahl = CookieManagement.GetAnzahl(HttpContext, Session);
            return View(reg);
        }

        public ActionResult Gast()
        {
            NameValueCollection nvc = Request.Form;

            Registrierung reg = new Registrierung
            {
                Role = "Gast",
                Vorname = nvc["vorname"],
                Nachname = nvc["nachname"],
                Geburtsjahr = nvc["geburtsjahr"],
                Geburtsmonat = nvc["geburtsmonat"],
                Geburtstag = nvc["geburtstag"],

                Email = nvc["email"],
                Nutzername = nvc["nutzername"],
                Password = nvc["password"],
                PasswordVerify = nvc["passwordVerify"],

                Grund = nvc["grund"]
            };

            reg.NewUser();

            ViewBag.Anzahl = CookieManagement.GetAnzahl(HttpContext, Session);
            return View(reg);
        }
    }
}

DBWT/Views/Home/Index.cshtml
@model DBWT.Models.Login

@{
    ViewBag.Name = "Start";
    ViewBag.Title = "e-Mensa - Start";
    ViewBag.Description = "Die Startseite der beliebten E-Mensa der FH Aachen.";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row middleElement20">
    <div class="col splash">
        <img title="Photo by Kevin Hou [MODIFIED]" src="~/Resources/Images/kevin-hou.jpg" alt="Titelbild (von Kevin Hou)" class="imageRound" />
    </div>
</div>
<div class="row middleElement20">
    <div class="col-4">
        <p id="text1" class="topElement">Der Dienst e-Mensa ist noch in der Beta. Sie können bereits @Html.ActionLink("Mahlzeiten", "Index", "Produkte") durchstöbern, aber noch nicht bestellen.</p>
    </div>
    <div class="col-8">
        <div class="form-row">
            <div class="col-8"><h2>Leckere Gerichte vorbestellen</h2><p>...und gemeinsam mit Freunden und Kommilitonen essen</p></div>
            <div class="col-4">
                @if (Model.signedIn)
                {
                    @Html.ActionLink(" Registrieren", "Index", "Registrierung", new { }, new { @class = "btn btn-primary fontawesome-hand-right buttonCenter linkedButton buttonColor2 topElement5 disabled disabled2" })
                    @Html.ActionLink(" Abmelden", "Index", "Login", new { }, new { @class = "btn btn-primary fontawesome-circle-arrow-right linkedButton buttonCenter buttonColor2 topElement" })
                }
                else
                {
                    @Html.ActionLink(" Registrieren", "Index", "Registrierung", new { }, new { @class = "btn btn-primary fontawesome-hand-right buttonCenter linkedButton buttonColor2 topElement5" })
                    @Html.ActionLink(" Anmelden", "Index", "Login", new { }, new { @class = "btn btn-primary fontawesome-circle-arrow-right linkedButton buttonCenter buttonColor2 topElement" })
                }
            </div>
        </div>
    </div>
</div>
<div class="row topElement20 bottomElement">
    <div class="col-4">
        @if (Model.signedIn)
        {
            <p class="topElement60">Sie sind bereits registriert und werden rechtzeitig über die Veröffentlichung des Dienstes per Mail informiert.</p>
        }
        else
        {
            <p class="topElement60">Registrieren Sie sich @Html.ActionLink("hier", "Index", "Registrierung"), um über die Veröffentlichung des Dienstes per Mail informiert zu werden.</p>
        }
    </div>
    <div class="col-8 splash">
        <img title="Photo by Bady QB [MODIFIED]" src="~/Resources/Images/bady-qb.jpg" alt="Neuigkeiten (von Bady QB)" class="imageRound" />
    </div>
</div>